# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: setup-conda
        # You may pin to the exact commit or the version.
        # uses: s-weigand/setup-conda@bf65a211e008297225b737b153801ac1231e9758
        uses: s-weigand/setup-conda@v1.0.5
        with:
          # Python version which should be installed with conda (default: 'Default')
          python-version: ${{ matrix.python-version }}
          # Additional channels like 'conda-forge' which can be used to install packages
          conda-channels: bioconda
      - run: which python
      - run: conda install conda-build anaconda-client
      - run: mkdir build-pkgs
      - run: conda build --output-folder build-pkgs/ conda/
      - run: anaconda upload -t ${{ secrets.ANACONDA_TOKEN }} --channel GAMB-GO build-pkgs/*.bz2
